### ISSUE TITLE
ToDo - Pages Feature List

### ISSUE THREAD

**Issue by newwby** [newwby/newwby.github.io#4]
## Features to Implement

**Task List**

---

- [ ] **Contents/Landing Page**

    - [x] Layout/design paper draft
    - [ ] Online CV
    - [ ] Contact Information
      - [ ] Email Form
    - [x] Portfolio Navigation Bar
    - [x] Implement Portfolio Segments/Links
      - [x] Web Tools
      - [x] Gamedev Projects
      - [x] Creative Writing
      - [x] Articles

---

- [x] **Index Refactor**

    - [X] [Figma draft](https://www.figma.com/design/BlusY0vsTySW0yT9frKHu7/GH.io-Web-Layout?node-id=0-1&t=22zBRgoFD6sL1Wc7-1)
    - [x] Header disappears as page scrolls - _possible but revisting whether desirable_
    - [x] Remove CV
    - [x] Change CV tab to 'Portfolio' or 'Main' on header/navbar
    - [x] Flexbox revamp
      - [x] Body Header Div
        - See Figma draft for layout
        - [x] Placeholder Header Block Div
        - [x] Complete Header Block layout
      - [x] Placeholder Content Block Div
        - [x] Div dividers
        - Dynamically built at runtime
        - ~~JSON for content pages~~
        - ~~Each page is a swipable (dot indicator, autoscroll when focused?) section on the content div~~
        - ~~Each page is a background image with a title/header at top left, and some body text at bottom right~~
        - ~~Each JSON entry has subentry for each page to add, keys in subentry are for URL, title, body~~
        _(JSON DB was unnecesary, use case too small)_
      - [x] Dynamic load fixed content block

---

- [ ] **Blog Implementation**

    - [ ] Landing page
    - [ ] Proof and publish blog about ChatGPT
    - [ ] Add navigation button to header/navbar
    - [ ] Implement header/navbar on blog
    - [ ] Blog navigation

---

- [ ] **SPA Conversion**

    - [ ] Index becomes a placeholder
    - [ ] Current index content block setup moved into separate page
    - [ ] Blog converted to load into index
    - [ ] Animations for page fade-out/fade-in on load

---

- [ ] **CCG/ICB Tool**

    -  ~~Hardcode full ICB db~~ _webscraper written, no longer planned_
    - [x] Layout/design paper draft
    - [x] Automatic focus to lookup field on load
    - [x] Enter key press confirms lookup
    - [x] Prompt in lookup field 'Please enter postcode, e.g. DJ12 3RU'
    - [x] make postcode field stretch/flex with window (leave space for results div though)
    - [ ] Credits/link to portfolio (built by Daniel Newby using postcodes.io, inspired by Stephen Keable)
    - [ ] Link to github directory (public)
    - [ ] Link to reporting issues
      - [ ] bug form automatically gets user device details
    - [ ] Re-do HTML/CSS to add more spacing and distinct sections
    - [ ] Improve font/bolding of CSS
    - [ ] Constituency lookup - revamp tool to be a more generic 'postcode' data form
    - [ ] [Support link](https://buymeacoffee.com/)?
    - [x] ICB DB webscraper script
    - [ ] GitHub Actions Webscraper for ICB DB (Monthly?)
    - [ ] postcode autocomplete?
    - ~~single page application~~
    - [ ] #6

**Comment by newwby** [comment]
Many of these CCG/ICB tool changes are no longer planned (not an efficient use of time) as ICB tool is going to be folded into a new comprehensive page (alongside [PCC Lookup](https://newwby.github.io/tools/pcc_lookup/index.html) tool) utilising [ORD API](https://digital.nhs.uk/developer/api-catalogue/organisation-data-service-ord). Will remove from the list once the new page is out of development.
